### ISSUE TITLE
add git actions workflow from gitlab-ci recipe

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-classifiers#1]
Rewrite same workflow for git-action
```yaml
# SEE other image versions in https://hub.docker.com/r/library/python/tags/
image: python:3.6

stages:
  - test
  - build


test:
  stage: test
  tags:
    - ubuntu_DOCKER
  before_script:
    - python3 -V
    - make testsenv
  script:
    - source .venv/bin/activate
    - make tests
  artifacts:
    reports:
      junit: out/pytest-junit.xml

bundle:
  stage: build
  needs:
    - test
  tags:
    - ubuntu_DOCKER
  before_script:
    - python3 -V
    - make testsenv
  script:
    - source .venv/bin/activate
    - make bundle
  artifacts:
    paths:
      - out/bundle.json
    untracked: false
    expire_in: 30 days
```
